version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=$http_proxy
    restart: on-failure
    container_name: 'junk_note_client'
    ports:
      - '$PORT:$PORT'
    tty: true
    command: yarn start
